# Generated by Django 4.1.2 on 2022-10-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_address'),
        ('backend', '0003_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Donar_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.donar'),
        ),
    ]
